config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: "homes#top"
  get 'home/about' => 'homes#about', as:'about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user #ユーザーに属する,1:N の「N」側にあたるモデル

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  has_one_attached :profile_image
  has_many :books, dependent: :destroy #1:N の「1」側にあたるモデルに、has_many,「dependent: :destroy」を付けて実装

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/NoImage.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about] #ログイン認証が済んでいない状態でこれらのページ以外にアクセスしても、ログイン画面へリダイレクト

  before_action :configure_permitted_parameters, if: :devise_controller?

  #サインイン後の遷移先
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  #サインアウト後の遷移先
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new #新規投稿はbookのindexページで行うからここに記述
    @books = Book.all #bookの一覧表示
    @user = current_user #現在ログインしているユーザーの編集
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id) #新規投稿したらbookのshowページに遷移
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id) #投稿の更新したらbookのshowページに遷移
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id]) #データ（レコード）を1件取得
    book.destroy #データ（レコード）を削除
    redirect_to books_path #ユーザーの詳細画面へリダイレクト
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @book = Book.new
    @user = current_user
    @users = User.all #Userの一覧表示
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id]) #ユーザーの取得
    if @user.update(user_params) #ユーザーのアップデート
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id) #ユーザーの詳細ページへのパス
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<% if user.name != "guestuser" %>
  <div class="row">
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  </div>
<% end %>

    <div class="row">
　　　<%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
　　　  <i class="fas fa-user-cog"></i>
　　　<% end %>
    </div>

    <h2 class="mt-3">New book</h2>

    <% if book.errors.any? %>
     <%= book.errors.count %>errors prohibited this obj from being saved:
     <ul>
      <% book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    <% end %>

    <%= form_with model: book do |f| %>
      <label for="book_title">Title</label><br>
     <%= f.text_field :title, class: "form-control book_title" %><br>
      <label for="book_body">Opinion</label><br>
     <%= f.text_area :body, class: "form-control book_title" %><br>
     <%= f.submit 'Create Book', class: "btn btn-success" %>
    <% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
       <%= @book.errors.count %>error prohibited this obj from being saved:
       <ul>
        <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
       </ul>
      <% end %>

      <%= form_with model: @book, method: :patch do |f| %>
       <label for="book_title">Title</label><br>
       <%= f.text_field :title, class: "form-control book_title" %><br>
       <label for="book_opinion">Opinion</label><br>
       <%= f.text_area :body, class: "form-control book_body"%><br>
       <%= f.submit 'Update Book', class: "btn btn-success" %>
      <% end %>

      <br>
      <%= link_to "Show", book_path %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'book', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan=3></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
               <%= image_tag book.user.get_profile_image(100, 100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'book', book: @book_new, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
     <table class="table">
      <tbody>
       <tr>
        <td>
         <%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image(100, 100) %><br>
          <%= @user.name %>
         <% end %>
        </td>
        <td>
         <%= link_to @book.title, book_path(@book.id) %>
        </td>
        <td>
         <%= @book.body %>
        </td>
        <td>
         <% if @book.user == current_user %>
          <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
         <% end %>
        </td>
        <td>
         <% if @book.user == current_user %>
          <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
         <% end %>
        </td>
       </tr>
      </tbody>
     </table>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
 <div class="row">
   <h1 class="px-3 mx-auto">
     Welcome to
     <i class="fas fa-book"></i>
     <strong>Bookers</strong>
     !
   </h1>
 </div>
</div>

app/views/homes/top.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
   <h1>
     welcome to
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>
     !!!
   </h1>
   <p>
     In
     <i class="fas fa-book"></i>
     <strong>Bookers</strong>
     ,
   </p>
   <p>you can share and exchange your opinions , inpressions , and emotions</p>
   <p>about various books!</p>
   <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
     <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
    </div>
    <div class="row">
     <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
    <div class="row">
     <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <a class="navbar-brand" href="/">
        <span>Bookers</span>
       </a>
       <button class="navbar-toggler" type="button" data-toggle="collapse"
       data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
       aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
           <i class="fas fa-home"></i>
           Home
          <% end %>
        </li>
        <li>
          <%= link_to users_path, class: "nav-link text-light" do %>
           <i class="fas fa-users"></i>
           Users
          <% end %>
        </li>
        <li>
          <%= link_to books_path, class: "nav-link text-light" do %>
           <i class="fas fa-book-open"></i>
           Books
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
           <i class="fas fa-sign-out-alt "></i>
           Log out
          <% end %>
        </li>
       <% else %>
        <li>
          <%= link_to "/", class: "nav-link text-light" do %>
           <i class="fas fa-home"></i>
           Home
          <% end %>
        </li>
        <li>
          <%= link_to about_path, class: "nav-link text-light" do %>
           <i class="fas fa-link"></i>
           About
          <% end %>
        </li>
        <li>
          <%= link_to "/users/sign_up", class: "nav-link text-light" do %>
           <i class="fas fa-user-plus"></i>
           Sign up
          <% end %>
        </li>
        <li>
          <%= link_to "/users/sign_in", class: "nav-link text-light" do %>
           <i class="fas fa-sign-in-alt"></i>
           Log in
          <% end %>
        </li>
       <% end %>
       </ul>
       </div>
      </div>
     </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
     <div class="container mt-5">
      <div class="row">
       <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
       </div>
      </div>
     </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>

      <% if @user.errors.any? %>
       <%= @user.errors.count %>error prohibited this obj from being saved:
       <ul>
        <% @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
       </ul>
      <% end %>

      <%= form_with model: @user do |f| %>
       <label for="user_name">Name</label><br>
       <%= f.text_field :name, class: "form-control name" %><br>
       <label for="user_image">Image</label><br>
       <%= f.file_field :profile_image, accept: "image/*" %><br>
       <label for="user_introdaction">Introduction</label><br>
       <%= f.text_area :introduction, class: "form-control introduction" %><br>
       <%= f.submit 'Update User', class: "btn btn-secondary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/book', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
             <%= image_tag user.get_profile_image(100, 100) %>
            </td>
            <td>
             <%= user.name %>
            </td>
            <td>
             <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
     <%= render 'books/book', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
               <%= image_tag @user.get_profile_image(100, 100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>